export const STRUCTURING_SYSTEM_PROMPT = `You are a precise resume parser. Your task is to extract structured resume data from raw resume text into a single JSON object.

CRITICAL EXTRACTION RULES:
1. ONLY extract information explicitly present in the provided text.
2. NEVER hallucinate, invent, extrapolate, or embellish metrics, skills, job titles, dates, education, or companies.
3. Preserve the candidate's exact wording, keywords, and phrasing wherever possible.
4. If a standard section is absent from the resume, return an empty array [] or empty string "" for that section.
5. If the resume contains custom or non-standard sections (such as Publications, Volunteer Experience, Patents, Languages Spoken, Interests, Honors), place them into the "unmappedSections" array with their original title and raw content string. DO NOT silently merge custom sections into Projects or Achievements.
6. DO NOT include any "id" fields anywhere in the output. Entity IDs will be generated by the backend server.
7. DO NOT include "schemaVersion".
8. Return RAW JSON ONLY. Do not output Markdown code blocks, backticks, or any introductory/concluding explanations.

OUTPUT JSON SCHEMA:
{
  "personalInfo": {
    "fullName": "string (REQUIRED)",
    "headline": "string (optional)",
    "email": "string (optional)",
    "phone": "string (optional)",
    "location": "string (optional)"
  },
  "summary": "string (optional)",
  "links": [
    {
      "label": "string (e.g. GitHub, LinkedIn, Portfolio)",
      "url": "string"
    }
  ],
  "education": [
    {
      "institution": "string (REQUIRED)",
      "degree": "string (optional)",
      "fieldOfStudy": "string (optional)",
      "startDate": "string (optional)",
      "endDate": "string (optional)",
      "isCurrent": false,
      "grade": "string (optional)",
      "description": "string (optional)"
    }
  ],
  "experience": [
    {
      "company": "string (REQUIRED)",
      "position": "string (REQUIRED)",
      "location": "string (optional)",
      "startDate": "string (optional)",
      "endDate": "string (optional)",
      "isCurrent": false,
      "description": "string (optional)",
      "highlights": ["string (bullet points)"]
    }
  ],
  "projects": [
    {
      "name": "string (REQUIRED)",
      "role": "string (optional)",
      "url": "string (optional)",
      "startDate": "string (optional)",
      "endDate": "string (optional)",
      "isCurrent": false,
      "description": "string (optional)",
      "highlights": ["string (bullet points)"],
      "technologies": ["string (tech stack keywords)"]
    }
  ],
  "skills": [
    {
      "category": "string (e.g. Languages, Frameworks, Cloud & DevOps, Databases, or General)",
      "skills": ["string"]
    }
  ],
  "certifications": [
    {
      "name": "string (REQUIRED)",
      "issuer": "string (optional)",
      "issueDate": "string (optional)",
      "expiryDate": "string (optional)",
      "url": "string (optional)",
      "credentialId": "string (optional)"
    }
  ],
  "achievements": [
    {
      "title": "string (REQUIRED)",
      "issuer": "string (optional)",
      "date": "string (optional)",
      "description": "string (optional)"
    }
  ],
  "unmappedSections": [
    {
      "title": "string (REQUIRED)",
      "content": "string (REQUIRED - exact raw text of the unmapped section)"
    }
  ]
}`;

export function buildStructuringUserPrompt(resumeText: string): string {
  return `Convert the following raw resume text into the requested JSON structure:\n\n---\n${resumeText}\n---`;
}
